const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "permission_groups_permissions",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "Permission_groups_permissions",
                        "childFields": [
                            
                                {
                                "name": "permission_group_permission_id",
                                "label": "Permission Group Permission Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "permission_groups_permissions_permissionGroupPermissionId",
                                "alias" : "permission_groups_permissions.permission_group_permission_id",
                                },
                                {
                                "name": "group_id",
                                "label": "Group Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "permission_groups_permissions_groupId",
                                "alias" : "permission_groups_permissions.group_id",
                                },
                                {
                                "name": "permission_id",
                                "label": "Permission Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "permission_groups_permissions_permissionId",
                                "alias" : "permission_groups_permissions.permission_id",
                                },
                                {
                                "name": "group_id",
                                "label": "Group Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "permission_groups_permissions_groupId",
                                "alias" : "permission_groups_permissions.group_id",
                                },
                                {
                                "name": "permission_id",
                                "label": "Permission Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "permission_groups_permissions_permissionId",
                                "alias" : "permission_groups_permissions.permission_id",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "permission_groups_permissions_updatedBy",
                                "alias" : "permission_groups_permissions.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'permission_groups_permissions_permissionGroupPermissionId' : 'permission_group_permission_id',  'permission_groups_permissions_groupId' : 'group_id',  'permission_groups_permissions_permissionId' : 'permission_id',  'permission_groups_permissions_status' : 'status',  'permission_groups_permissions_groupId' : 'group_id',  'permission_groups_permissions_permissionId' : 'permission_id',  'permission_groups_permissions_status' : 'status',  'permission_groups_permissions_updatedBy' : 'updated_by',  'permission_groups_permissions_updatedAt' : 'updated_at',  'permission_groups_permissions_createdAt' : 'created_at'}"
            };
            module.exports = parameters;