const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "task_history",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "Task_history",
                        "childFields": [
                            
                                {
                                "name": "task_history_id",
                                "label": "Task History Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_history_taskHistoryId",
                                "alias" : "task_history.task_history_id",
                                },
                                {
                                "name": "task_id",
                                "label": "Task Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_history_taskId",
                                "alias" : "task_history.task_id",
                                },
                                {
                                "name": "task_flow_step_id",
                                "label": "Task Flow Step Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_history_taskFlowStepId",
                                "alias" : "task_history.task_flow_step_id",
                                },
                                {
                                "name": "action",
                                "label": "Action",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_history_action",
                                "alias" : "task_history.action",
                                },
                                {
                                "name": "action_by_user_role_designation_department_id",
                                "label": "Action By User Role Designation Department Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_history_actionByUserRoleDesignationDepartmentId",
                                "alias" : "task_history.action_by_user_role_designation_department_id",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_history_updatedBy",
                                "alias" : "task_history.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'task_history_taskHistoryId' : 'task_history_id',  'task_history_taskId' : 'task_id',  'task_history_taskFlowStepId' : 'task_flow_step_id',  'task_history_action' : 'action',  'task_history_status' : 'status',  'task_history_actionByUserRoleDesignationDepartmentId' : 'action_by_user_role_designation_department_id',  'task_history_updatedAt' : 'updated_at',  'task_history_createdAt' : 'created_at',  'task_history_updatedBy' : 'updated_by'}"
            };
            module.exports = parameters;