const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "user_role_designation_permissions",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "User_role_designation_permissions",
                        "childFields": [
                            
                                {
                                "name": "user_role_designation_permission_id",
                                "label": "User Role Designation Permission Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_role_designation_permissions_userRoleDesignationPermissionId",
                                "alias" : "user_role_designation_permissions.user_role_designation_permission_id",
                                },
                                {
                                "name": "user_role_designation_department_id",
                                "label": "User Role Designation Department Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_role_designation_permissions_userRoleDesignationDepartmentId",
                                "alias" : "user_role_designation_permissions.user_role_designation_department_id",
                                },
                                {
                                "name": "permission_id",
                                "label": "Permission Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_role_designation_permissions_permissionId",
                                "alias" : "user_role_designation_permissions.permission_id",
                                },
                                {
                                "name": "user_role_designation_department_id",
                                "label": "User Role Designation Department Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_role_designation_permissions_userRoleDesignationDepartmentId",
                                "alias" : "user_role_designation_permissions.user_role_designation_department_id",
                                },
                                {
                                "name": "permission_id",
                                "label": "Permission Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_role_designation_permissions_permissionId",
                                "alias" : "user_role_designation_permissions.permission_id",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_role_designation_permissions_updatedBy",
                                "alias" : "user_role_designation_permissions.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'user_role_designation_permissions_userRoleDesignationPermissionId' : 'user_role_designation_permission_id',  'user_role_designation_permissions_userRoleDesignationDepartmentId' : 'user_role_designation_department_id',  'user_role_designation_permissions_permissionId' : 'permission_id',  'user_role_designation_permissions_status' : 'status',  'user_role_designation_permissions_userRoleDesignationDepartmentId' : 'user_role_designation_department_id',  'user_role_designation_permissions_permissionId' : 'permission_id',  'user_role_designation_permissions_status' : 'status',  'user_role_designation_permissions_updatedBy' : 'updated_by',  'user_role_designation_permissions_updatedAt' : 'updated_at',  'user_role_designation_permissions_createdAt' : 'created_at'}"
            };
            module.exports = parameters;