const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "tasks",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "Tasks",
                        "childFields": [
                            
                                {
                                "name": "task_id",
                                "label": "Task Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "tasks_taskId",
                                "alias" : "tasks.task_id",
                                },
                                {
                                "name": "task_title",
                                "label": "Task Title",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "tasks_taskTitle",
                                "alias" : "tasks.task_title",
                                },
                                {
                                "name": "task_title",
                                "label": "Task Title",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "tasks_taskTitle",
                                "alias" : "tasks.task_title",
                                },
                                {
                                "name": "type",
                                "label": "Type",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "tasks_type",
                                "alias" : "tasks.type",
                                },
                                {
                                "name": "task_description",
                                "label": "Task Description",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "tasks_taskDescription",
                                "alias" : "tasks.task_description",
                                },
                                {
                                "name": "parent_task_id",
                                "label": "Parent Task Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "tasks_parentTaskId",
                                "alias" : "tasks.parent_task_id",
                                },
                                {
                                "name": "attachement_id",
                                "label": "Attachement Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "tasks_attachementId",
                                "alias" : "tasks.attachement_id",
                                },
                                {
                                "name": "task_flow_id",
                                "label": "Task Flow Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "tasks_taskFlowId",
                                "alias" : "tasks.task_flow_id",
                                },
                                {
                                "name": "task_assigned_to_user_role_designation_department_id",
                                "label": "Task Assigned To User Role Designation Department Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "tasks_taskAssignedToUserRoleDesignationDepartmentId",
                                "alias" : "tasks.task_assigned_to_user_role_designation_department_id",
                                },
                                {
                                "name": "created_by_user_role_designation_department_id",
                                "label": "Created By User Role Designation Department Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "tasks_createdByUserRoleDesignationDepartmentId",
                                "alias" : "tasks.created_by_user_role_designation_department_id",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "tasks_updatedBy",
                                "alias" : "tasks.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'tasks_taskId' : 'task_id',  'tasks_taskTitle' : 'task_title',  'tasks_status' : 'status',  'tasks_taskTitle' : 'task_title',  'tasks_status' : 'status',  'tasks_type' : 'type',  'tasks_taskDescription' : 'task_description',  'tasks_parentTaskId' : 'parent_task_id',  'tasks_attachementId' : 'attachement_id',  'tasks_taskFlowId' : 'task_flow_id',  'tasks_taskAssignedToUserRoleDesignationDepartmentId' : 'task_assigned_to_user_role_designation_department_id',  'tasks_createdByUserRoleDesignationDepartmentId' : 'created_by_user_role_designation_department_id',  'tasks_updatedAt' : 'updated_at',  'tasks_createdAt' : 'created_at',  'tasks_updatedBy' : 'updated_by'}"
            };
            module.exports = parameters;