const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "inventory_sub_category_items",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "Inventory_sub_category_items",
                        "childFields": [
                            
                                {
                                "name": "inventory_sub_category_item_id",
                                "label": "Inventory Sub Category Item Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_sub_category_items_inventorySubCategoryItemId",
                                "alias" : "inventory_sub_category_items.inventory_sub_category_item_id",
                                },
                                {
                                "name": "inventory_sub_category_id",
                                "label": "Inventory Sub Category Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_sub_category_items_inventorySubCategoryId",
                                "alias" : "inventory_sub_category_items.inventory_sub_category_id",
                                },
                                {
                                "name": "parent_inventory_sub_category_item_id",
                                "label": "Parent Inventory Sub Category Item Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_sub_category_items_parentInventorySubCategoryItemId",
                                "alias" : "inventory_sub_category_items.parent_inventory_sub_category_item_id",
                                },
                                {
                                "name": "item_location_id",
                                "label": "Item Location Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_sub_category_items_itemLocationId",
                                "alias" : "inventory_sub_category_items.item_location_id",
                                },
                                {
                                "name": "inventory_bill_id",
                                "label": "Inventory Bill Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_sub_category_items_inventoryBillId",
                                "alias" : "inventory_sub_category_items.inventory_bill_id",
                                },
                                {
                                "name": "inventory_sub_category_item_name",
                                "label": "Inventory Sub Category Item Name",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_sub_category_items_inventorySubCategoryItemName",
                                "alias" : "inventory_sub_category_items.inventory_sub_category_item_name",
                                },
                                {
                                "name": "company_name",
                                "label": "Company Name",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_sub_category_items_companyName",
                                "alias" : "inventory_sub_category_items.company_name",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_sub_category_items_updatedBy",
                                "alias" : "inventory_sub_category_items.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'inventory_sub_category_items_inventorySubCategoryItemId' : 'inventory_sub_category_item_id',  'inventory_sub_category_items_inventorySubCategoryId' : 'inventory_sub_category_id',  'inventory_sub_category_items_parentInventorySubCategoryItemId' : 'parent_inventory_sub_category_item_id',  'inventory_sub_category_items_itemLocationId' : 'item_location_id',  'inventory_sub_category_items_inventoryBillId' : 'inventory_bill_id',  'inventory_sub_category_items_inventorySubCategoryItemName' : 'inventory_sub_category_item_name',  'inventory_sub_category_items_companyName' : 'company_name',  'inventory_sub_category_items_status' : 'status',  'inventory_sub_category_items_updatedBy' : 'updated_by',  'inventory_sub_category_items_updatedAt' : 'updated_at',  'inventory_sub_category_items_createdAt' : 'created_at'}"
            };
            module.exports = parameters;