const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "task_flows",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "Task_flows",
                        "childFields": [
                            
                                {
                                "name": "task_flow_id",
                                "label": "Task Flow Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flows_taskFlowId",
                                "alias" : "task_flows.task_flow_id",
                                },
                                {
                                "name": "task_flow_title",
                                "label": "Task Flow Title",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flows_taskFlowTitle",
                                "alias" : "task_flows.task_flow_title",
                                },
                                {
                                "name": "task_flow_title",
                                "label": "Task Flow Title",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flows_taskFlowTitle",
                                "alias" : "task_flows.task_flow_title",
                                },
                                {
                                "name": "task_flow_description",
                                "label": "Task Flow Description",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flows_taskFlowDescription",
                                "alias" : "task_flows.task_flow_description",
                                },
                                {
                                "name": "is_default",
                                "label": "Is Default",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flows_isDefault",
                                "alias" : "task_flows.is_default",
                                },
                                {
                                "name": "created_by_user_role_designation_department_id",
                                "label": "Created By User Role Designation Department Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flows_createdByUserRoleDesignationDepartmentId",
                                "alias" : "task_flows.created_by_user_role_designation_department_id",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flows_updatedBy",
                                "alias" : "task_flows.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'task_flows_taskFlowId' : 'task_flow_id',  'task_flows_taskFlowTitle' : 'task_flow_title',  'task_flows_status' : 'status',  'task_flows_taskFlowTitle' : 'task_flow_title',  'task_flows_status' : 'status',  'task_flows_taskFlowDescription' : 'task_flow_description',  'task_flows_isDefault' : 'is_default',  'task_flows_createdByUserRoleDesignationDepartmentId' : 'created_by_user_role_designation_department_id',  'task_flows_updatedAt' : 'updated_at',  'task_flows_createdAt' : 'created_at',  'task_flows_updatedBy' : 'updated_by'}"
            };
            module.exports = parameters;