export const parameters = {
              "steps": [
                
                    {
                        "title": "inventory_sub_category_items Info",
                        "parameters": {
                            "fields": [
                                {
                                    "name": "inventorySubCategoryItems",
                                    "type": "section",
                                    "hideInCreateForm": false,
                                    "visible": false,
                                    "required": false,
                                    "disabled": false,
                                    "validations": "",
                                    "dependancyCheck": false,
                                    "isPrefilled": false,
                                    "source": "req.body",
                                    "title": "InventorySubCategoryItems",
                                    "childFields": [
                                            {
                                              "name": "id",
                                              "label": "id",
                                              "title": "",
                                              "type": "textField",
                                              "required": false,
                                              "hideInCreateForm": true,
                                              "hideInViewForm" : true,
                                              "visible": false,
                                              "disabled": false,
                                              "dependancyCheck": false,
                                              "isPrefilled": false,
                                              "source": "req.query",
                                              "min": "",
                                              "max": "",
                                              "selectServer": false,
                                              "dynamicKey": "id",
                                              "alias" : "inventory_sub_category_items.id"

                                            },
                                        
                                            {
                                                "name": "inventorySubCategoryId",
                                                "label": "Inventory Sub Category Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "inventorySubCategoryItems_inventorySubCategoryId",
                                                "alias" : "inventory_sub_category_items.inventory_sub_category_id"
                                            },
                                            {
                                                "name": "parentInventorySubCategoryItemId",
                                                "label": "Parent Inventory Sub Category Item Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "inventorySubCategoryItems_parentInventorySubCategoryItemId",
                                                "alias" : "inventory_sub_category_items.parent_inventory_sub_category_item_id"
                                            },
                                            {
                                                "name": "itemLocationId",
                                                "label": "Item Location Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "inventorySubCategoryItems_itemLocationId",
                                                "alias" : "inventory_sub_category_items.item_location_id"
                                            },
                                            {
                                                "name": "inventoryBillId",
                                                "label": "Inventory Bill Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "inventorySubCategoryItems_inventoryBillId",
                                                "alias" : "inventory_sub_category_items.inventory_bill_id"
                                            },
                                            {
                                                "name": "inventorySubCategoryItemName",
                                                "label": "Inventory Sub Category Item Name",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "inventorySubCategoryItems_inventorySubCategoryItemName",
                                                "alias" : "inventory_sub_category_items.inventory_sub_category_item_name"
                                            },
                                            {
                                                "name": "companyName",
                                                "label": "Company Name",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "inventorySubCategoryItems_companyName",
                                                "alias" : "inventory_sub_category_items.company_name"
                                            },
                                            {
                                              "type": "listOfFields",
                                              "name": "options",
                                              "label": "Add Inventory Sub Category Items",
                                              "hideInCreateForm": true,

                                              "hideInViewForm": true,
                                              "title": "Select Inventory Sub Category Items",
                                              "dependancyCheck": false,
                                              "childFields": [
                                            
                                            ]
                                          }
                                        ,
                                        
                                            {
                                                "name": "updatedBy",
                                                "label": "Updated By",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "inventorySubCategoryItems_updatedBy",
                                                "alias" : "inventory_sub_category_items.updated_by"
                                            },
                                            {
                                                "name": "updatedAt",
                                                "label": "Updated At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "inventorySubCategoryItems_updatedAt",
                                                "alias" : "inventory_sub_category_items.updated_at"
                                            },
                                            {
                                                "name": "createdAt",
                                                "label": "Created At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "inventorySubCategoryItems_createdAt",
                                                "alias" : "inventory_sub_category_items.created_at"
                                            },
                                          
                                            {
                                                "name": "status",
                                                "label": "Status",
                                                "title": "",
                                                "type": "select",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "inventorySubCategoryItems_status",
                                                options:[
                                                    {value:'inactive',label:'inactive'},
                                                    {value:'active',label:'active'}
                                                ],
                                                "alias" : "inventory_sub_category_items.status"
                                            }

                                    ]
                                }
                            ]
                        },
                        "permission": "inventory_sub_category_items_view"
                    }                  
              ],
              "colMapper": { 'inventory_sub_category_items_inventorySubCategoryItemId' : 'inventory_sub_category_item_id',  'inventory_sub_category_items_inventorySubCategoryId' : 'inventory_sub_category_id',  'inventory_sub_category_items_parentInventorySubCategoryItemId' : 'parent_inventory_sub_category_item_id',  'inventory_sub_category_items_itemLocationId' : 'item_location_id',  'inventory_sub_category_items_inventoryBillId' : 'inventory_bill_id',  'inventory_sub_category_items_inventorySubCategoryItemName' : 'inventory_sub_category_item_name',  'inventory_sub_category_items_companyName' : 'company_name',  'inventory_sub_category_items_status' : 'status',  'inventory_sub_category_items_updatedBy' : 'updated_by',  'inventory_sub_category_items_updatedAt' : 'updated_at',  'inventory_sub_category_items_createdAt' : 'created_at'}
          };