export const parameters = {
              "steps": [
                
                    {
                        "title": "task_tags Info",
                        "parameters": {
                            "fields": [
                                {
                                    "name": "taskTags",
                                    "type": "section",
                                    "hideInCreateForm": false,
                                    "visible": false,
                                    "required": false,
                                    "disabled": false,
                                    "validations": "",
                                    "dependancyCheck": false,
                                    "isPrefilled": false,
                                    "source": "req.body",
                                    "title": "TaskTags",
                                    "childFields": [
                                            {
                                              "name": "id",
                                              "label": "id",
                                              "title": "",
                                              "type": "textField",
                                              "required": false,
                                              "hideInCreateForm": true,
                                              "hideInViewForm" : true,
                                              "visible": false,
                                              "disabled": false,
                                              "dependancyCheck": false,
                                              "isPrefilled": false,
                                              "source": "req.query",
                                              "min": "",
                                              "max": "",
                                              "selectServer": false,
                                              "dynamicKey": "id",
                                              "alias" : "task_tags.id"

                                            },
                                        
                                            {
                                                "name": "tag",
                                                "label": "Tag",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskTags_tag",
                                                "alias" : "task_tags.tag"
                                            },
                                            {
                                              "type": "listOfFields",
                                              "name": "options",
                                              "label": "Add Task Tags",
                                              "hideInCreateForm": false,

                                              "hideInViewForm": false,
                                              "title": "Select Task Tags",
                                              "dependancyCheck": false,
                                              "childFields": [
                                            
                                                {
                                                    "name": "taskId",
                                                    "label": "Task Id",
                                                    "title": "",
                                                    "type": "select",
                                                    "required": false,
                                                    "hideInCreateForm": false,
                                                    "hideInViewForm": true,
                                                    "visible": false,
                                                    "disabled": false,
                                                    "dependancyCheck": false,
                                                    "isPrefilled": false,
                                                    "source": "req.body",
                                                    "min": "",
                                                    "max": "",
                                                    "validations": [],
                                                    "selectServer": true,
                                                    "dynamicKey": "taskTags_taskId",
                                                    "selectServerUrl": "/list/tasks_n/dropdown?version=1.0",
                                                    "alias" : "task_tags.task_id"
                                                }
                                                
                                                
                                            ]
                                          }
                                        ,
                                        
                                            {
                                                "name": "updatedBy",
                                                "label": "Updated By",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskTags_updatedBy",
                                                "alias" : "task_tags.updated_by"
                                            },
                                            {
                                                "name": "updatedAt",
                                                "label": "Updated At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskTags_updatedAt",
                                                "alias" : "task_tags.updated_at"
                                            },
                                            {
                                                "name": "createdAt",
                                                "label": "Created At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskTags_createdAt",
                                                "alias" : "task_tags.created_at"
                                            },
                                          
                                            {
                                                "name": "status",
                                                "label": "Status",
                                                "title": "",
                                                "type": "select",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskTags_status",
                                                options:[
                                                    {value:'inactive',label:'inactive'},
                                                    {value:'active',label:'active'}
                                                ],
                                                "alias" : "task_tags.status"
                                            }

                                    ]
                                }
                            ]
                        },
                        "permission": "task_tags_view"
                    },
                    {
                        "title": "tasks_n Info",
                        "parameters": {
                            "fields": [
                                {
                                    "name": "tasksN",
                                    "type": "section",
                                    "hideInCreateForm": false,
                                    "visible": false,
                                    "required": false,
                                    "disabled": false,
                                    "validations": "",
                                    "dependancyCheck": false,
                                    "isPrefilled": false,
                                    "source": "req.body",
                                    "title": "TaskTags",
                                    "childFields": [
                                            {
                                              "name": "id",
                                              "label": "id",
                                              "title": "",
                                              "type": "textField",
                                              "required": false,
                                              "hideInCreateForm": true,
                                              "hideInViewForm" : true,
                                              "visible": false,
                                              "disabled": false,
                                              "dependancyCheck": false,
                                              "isPrefilled": false,
                                              "source": "req.query",
                                              "min": "",
                                              "max": "",
                                              "selectServer": false,
                                              "dynamicKey": "id",
                                              "alias" : "tasks_n.id"

                                            },
                                        
                                            {
                                                "name": "title",
                                                "label": "Title",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "tasksN_title",
                                                "alias" : "tasks_n.title"
                                            },
                                            {
                                                "name": "description",
                                                "label": "Description",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "tasksN_description",
                                                "alias" : "tasks_n.description"
                                            },
                                            {
                                                "name": "priority",
                                                "label": "Priority",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "tasksN_priority",
                                                "alias" : "tasks_n.priority"
                                            },
                                            {
                                                "name": "dueDate",
                                                "label": "Due Date",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "tasksN_dueDate",
                                                "alias" : "tasks_n.due_date"
                                            },
                                            {
                                              "type": "listOfFields",
                                              "name": "options",
                                              "label": "Add Tasks N",
                                              "hideInCreateForm": false,

                                              "hideInViewForm": false,
                                              "title": "Select Tasks N",
                                              "dependancyCheck": false,
                                              "childFields": [
                                            
                                                {
                                                    "name": "createdBy",
                                                    "label": "Created By",
                                                    "title": "",
                                                    "type": "select",
                                                    "required": false,
                                                    "hideInCreateForm": false,
                                                    "hideInViewForm": true,
                                                    "visible": false,
                                                    "disabled": false,
                                                    "dependancyCheck": false,
                                                    "isPrefilled": false,
                                                    "source": "req.body",
                                                    "min": "",
                                                    "max": "",
                                                    "validations": [],
                                                    "selectServer": true,
                                                    "dynamicKey": "tasksN_createdBy",
                                                    "selectServerUrl": "/list/users/dropdown?version=1.0",
                                                    "alias" : "tasks_n.created_by"
                                                }
                                                ,
                                                {
                                                    "name": "firstName",
                                                    "label": "First Name",
                                                    "title": "",
                                                    "type": "textField",
                                                    "required": false,
                                                    "hideInCreateForm": true,
                                                    "hideInViewForm": false,
                                                    "visible": true,
                                                    "disabled": false,
                                                    "dependancyCheck": false,
                                                    "isPrefilled": false,
                                                    "source": "req.body",
                                                    "min": "",
                                                    "max": "",
                                                    "validations": [],
                                                    "dynamicKey" : "tasksN_FirstName",
                                                    "selectServer": false,
                                                    "alias" : "tasks_n.created_by"
                                                }
                                                ,
                                                {
                                                    "name": "assigneeId",
                                                    "label": "Assignee Id",
                                                    "title": "",
                                                    "type": "select",
                                                    "required": false,
                                                    "hideInCreateForm": false,
                                                    "hideInViewForm": true,
                                                    "visible": false,
                                                    "disabled": false,
                                                    "dependancyCheck": false,
                                                    "isPrefilled": false,
                                                    "source": "req.body",
                                                    "min": "",
                                                    "max": "",
                                                    "validations": [],
                                                    "selectServer": true,
                                                    "dynamicKey": "tasksN_assigneeId",
                                                    "selectServerUrl": "/list/users/dropdown?version=1.0",
                                                    "alias" : "tasks_n.assignee_id"
                                                }
                                                ,
                                                {
                                                    "name": "firstName",
                                                    "label": "First Name",
                                                    "title": "",
                                                    "type": "textField",
                                                    "required": false,
                                                    "hideInCreateForm": true,
                                                    "hideInViewForm": false,
                                                    "visible": true,
                                                    "disabled": false,
                                                    "dependancyCheck": false,
                                                    "isPrefilled": false,
                                                    "source": "req.body",
                                                    "min": "",
                                                    "max": "",
                                                    "validations": [],
                                                    "dynamicKey" : "tasksN_FirstName",
                                                    "selectServer": false,
                                                    "alias" : "tasks_n.assignee_id"
                                                }
                                                ,
                                                {
                                                    "name": "projectId",
                                                    "label": "Project Id",
                                                    "title": "",
                                                    "type": "select",
                                                    "required": false,
                                                    "hideInCreateForm": false,
                                                    "hideInViewForm": true,
                                                    "visible": false,
                                                    "disabled": false,
                                                    "dependancyCheck": false,
                                                    "isPrefilled": false,
                                                    "source": "req.body",
                                                    "min": "",
                                                    "max": "",
                                                    "validations": [],
                                                    "selectServer": true,
                                                    "dynamicKey": "tasksN_projectId",
                                                    "selectServerUrl": "/list/projects/dropdown?version=1.0",
                                                    "alias" : "tasks_n.project_id"
                                                }
                                                ,
                                                {
                                                    "name": "name",
                                                    "label": "Name",
                                                    "title": "",
                                                    "type": "textField",
                                                    "required": false,
                                                    "hideInCreateForm": true,
                                                    "hideInViewForm": false,
                                                    "visible": true,
                                                    "disabled": false,
                                                    "dependancyCheck": false,
                                                    "isPrefilled": false,
                                                    "source": "req.body",
                                                    "min": "",
                                                    "max": "",
                                                    "validations": [],
                                                    "dynamicKey" : "tasksN_Name",
                                                    "selectServer": false,
                                                    "alias" : "tasks_n.project_id"
                                                }
                                                
                                            ]
                                          }
                                        ,
                                        
                                            {
                                                "name": "updatedBy",
                                                "label": "Updated By",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "tasksN_updatedBy",
                                                "alias" : "tasks_n.updated_by"
                                            },
                                            {
                                                "name": "updatedAt",
                                                "label": "Updated At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "tasksN_updatedAt",
                                                "alias" : "tasks_n.updated_at"
                                            },
                                            {
                                                "name": "createdAt",
                                                "label": "Created At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "tasksN_createdAt",
                                                "alias" : "tasks_n.created_at"
                                            },
                                          
                                            {
                                                "name": "status",
                                                "label": "Status",
                                                "title": "",
                                                "type": "select",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "tasksN_status",
                                                options:[
                                                    {value:'inactive',label:'inactive'},
                                                    {value:'active',label:'active'}
                                                ],
                                                "alias" : "tasks_n.status"
                                            }

                                    ]
                                }
                            ]
                        },
                        "permission": "tasks_n_view"
                    }                  
              ],
              "colMapper": { 'task_tags_tagId' : 'tag_id',  'task_tags_taskId' : 'task_id',  'task_tags_tag' : 'tag',  'task_tags_status' : 'status',  'task_tags_updatedBy' : 'updated_by',  'task_tags_updatedAt' : 'updated_at',  'task_tags_createdAt' : 'created_at',  'tasks_n_taskId' : 'task_id',  'tasks_n_createdBy' : 'created_by',  'tasks_n_assigneeId' : 'assignee_id',  'tasks_n_projectId' : 'project_id',  'tasks_n_title' : 'title',  'tasks_n_description' : 'description',  'tasks_n_status' : 'status',  'tasks_n_priority' : 'priority',  'tasks_n_dueDate' : 'due_date',  'tasks_n_updatedBy' : 'updated_by',  'tasks_n_updatedAt' : 'updated_at',  'tasks_n_createdAt' : 'created_at'}
          };