const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "item_maintenance",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "Item_maintenance",
                        "childFields": [
                            
                                {
                                "name": "item_maintenance_id",
                                "label": "Item Maintenance Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_maintenance_itemMaintenanceId",
                                "alias" : "item_maintenance.item_maintenance_id",
                                },
                                {
                                "name": "task_id",
                                "label": "Task Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_maintenance_taskId",
                                "alias" : "item_maintenance.task_id",
                                },
                                {
                                "name": "inventory_sub_category_item_id",
                                "label": "Inventory Sub Category Item Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_maintenance_inventorySubCategoryItemId",
                                "alias" : "item_maintenance.inventory_sub_category_item_id",
                                },
                                {
                                "name": "user_role_designation_department_id",
                                "label": "User Role Designation Department Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_maintenance_userRoleDesignationDepartmentId",
                                "alias" : "item_maintenance.user_role_designation_department_id",
                                },
                                {
                                "name": "inventory_bill_id",
                                "label": "Inventory Bill Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_maintenance_inventoryBillId",
                                "alias" : "item_maintenance.inventory_bill_id",
                                },
                                {
                                "name": "description",
                                "label": "Description",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_maintenance_description",
                                "alias" : "item_maintenance.description",
                                },
                                {
                                "name": "maintenance_date",
                                "label": "Maintenance Date",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_maintenance_maintenanceDate",
                                "alias" : "item_maintenance.maintenance_date",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_maintenance_updatedBy",
                                "alias" : "item_maintenance.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'item_maintenance_itemMaintenanceId' : 'item_maintenance_id',  'item_maintenance_taskId' : 'task_id',  'item_maintenance_inventorySubCategoryItemId' : 'inventory_sub_category_item_id',  'item_maintenance_userRoleDesignationDepartmentId' : 'user_role_designation_department_id',  'item_maintenance_inventoryBillId' : 'inventory_bill_id',  'item_maintenance_description' : 'description',  'item_maintenance_maintenanceDate' : 'maintenance_date',  'item_maintenance_status' : 'status',  'item_maintenance_updatedBy' : 'updated_by',  'item_maintenance_updatedAt' : 'updated_at',  'item_maintenance_createdAt' : 'created_at'}"
            };
            module.exports = parameters;