export const parameters = {
              "steps": [
                
                    {
                        "title": "task_flow_steps Info",
                        "parameters": {
                            "fields": [
                                {
                                    "name": "taskFlowSteps",
                                    "type": "section",
                                    "hideInCreateForm": false,
                                    "visible": false,
                                    "required": false,
                                    "disabled": false,
                                    "validations": "",
                                    "dependancyCheck": false,
                                    "isPrefilled": false,
                                    "source": "req.body",
                                    "title": "TaskFlowSteps",
                                    "childFields": [
                                            {
                                              "name": "id",
                                              "label": "id",
                                              "title": "",
                                              "type": "textField",
                                              "required": false,
                                              "hideInCreateForm": true,
                                              "hideInViewForm" : true,
                                              "visible": false,
                                              "disabled": false,
                                              "dependancyCheck": false,
                                              "isPrefilled": false,
                                              "source": "req.query",
                                              "min": "",
                                              "max": "",
                                              "selectServer": false,
                                              "dynamicKey": "id",
                                              "alias" : "task_flow_steps.id"

                                            },
                                        
                                            {
                                                "name": "taskFlowId",
                                                "label": "Task Flow Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskFlowSteps_taskFlowId",
                                                "alias" : "task_flow_steps.task_flow_id"
                                            },
                                            {
                                                "name": "stepTitle",
                                                "label": "Step Title",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskFlowSteps_stepTitle",
                                                "alias" : "task_flow_steps.step_title"
                                            },
                                            {
                                                "name": "stepOrder",
                                                "label": "Step Order",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskFlowSteps_stepOrder",
                                                "alias" : "task_flow_steps.step_order"
                                            },
                                            {
                                                "name": "stepDescription",
                                                "label": "Step Description",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskFlowSteps_stepDescription",
                                                "alias" : "task_flow_steps.step_description"
                                            },
                                            {
                                                "name": "isCrossDepartment",
                                                "label": "Is Cross Department",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskFlowSteps_isCrossDepartment",
                                                "alias" : "task_flow_steps.is_cross_department"
                                            },
                                            {
                                                "name": "stepAssignedToRoleDepartmentId",
                                                "label": "Step Assigned To Role Department Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskFlowSteps_stepAssignedToRoleDepartmentId",
                                                "alias" : "task_flow_steps.step_assigned_to_role_department_id"
                                            },
                                            {
                                                "name": "createdByUserRoleDepartmentId",
                                                "label": "Created By User Role Department Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskFlowSteps_createdByUserRoleDepartmentId",
                                                "alias" : "task_flow_steps.created_by_user_role_department_id"
                                            },
                                            {
                                              "type": "listOfFields",
                                              "name": "options",
                                              "label": "Add Task Flow Steps",
                                              "hideInCreateForm": true,

                                              "hideInViewForm": true,
                                              "title": "Select Task Flow Steps",
                                              "dependancyCheck": false,
                                              "childFields": [
                                            
                                            ]
                                          }
                                        ,
                                        
                                            {
                                                "name": "updatedAt",
                                                "label": "Updated At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskFlowSteps_updatedAt",
                                                "alias" : "task_flow_steps.updated_at"
                                            },
                                            {
                                                "name": "createdAt",
                                                "label": "Created At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskFlowSteps_createdAt",
                                                "alias" : "task_flow_steps.created_at"
                                            },
                                            {
                                                "name": "updatedBy",
                                                "label": "Updated By",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskFlowSteps_updatedBy",
                                                "alias" : "task_flow_steps.updated_by"
                                            },
                                          
                                            {
                                                "name": "status",
                                                "label": "Status",
                                                "title": "",
                                                "type": "select",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "taskFlowSteps_status",
                                                options:[
                                                    {value:'inactive',label:'inactive'},
                                                    {value:'active',label:'active'}
                                                ],
                                                "alias" : "task_flow_steps.status"
                                            }

                                    ]
                                }
                            ]
                        },
                        "permission": "task_flow_steps_view"
                    }                  
              ],
              "colMapper": { 'task_flow_steps_taskFlowStepId' : 'task_flow_step_id',  'task_flow_steps_taskFlowId' : 'task_flow_id',  'task_flow_steps_stepTitle' : 'step_title',  'task_flow_steps_stepOrder' : 'step_order',  'task_flow_steps_status' : 'status',  'task_flow_steps_stepDescription' : 'step_description',  'task_flow_steps_isCrossDepartment' : 'is_cross_department',  'task_flow_steps_stepAssignedToRoleDepartmentId' : 'step_assigned_to_role_department_id',  'task_flow_steps_createdByUserRoleDepartmentId' : 'created_by_user_role_department_id',  'task_flow_steps_updatedAt' : 'updated_at',  'task_flow_steps_createdAt' : 'created_at',  'task_flow_steps_updatedBy' : 'updated_by'}
          };