export const parameters = {
              "steps": [
                
                    {
                        "title": "item_maintenance Info",
                        "parameters": {
                            "fields": [
                                {
                                    "name": "itemMaintenance",
                                    "type": "section",
                                    "hideInCreateForm": false,
                                    "visible": false,
                                    "required": false,
                                    "disabled": false,
                                    "validations": "",
                                    "dependancyCheck": false,
                                    "isPrefilled": false,
                                    "source": "req.body",
                                    "title": "ItemMaintenance",
                                    "childFields": [
                                            {
                                              "name": "id",
                                              "label": "id",
                                              "title": "",
                                              "type": "textField",
                                              "required": false,
                                              "hideInCreateForm": true,
                                              "hideInViewForm" : true,
                                              "visible": false,
                                              "disabled": false,
                                              "dependancyCheck": false,
                                              "isPrefilled": false,
                                              "source": "req.query",
                                              "min": "",
                                              "max": "",
                                              "selectServer": false,
                                              "dynamicKey": "id",
                                              "alias" : "item_maintenance.id"

                                            },
                                        
                                            {
                                                "name": "taskId",
                                                "label": "Task Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemMaintenance_taskId",
                                                "alias" : "item_maintenance.task_id"
                                            },
                                            {
                                                "name": "inventorySubCategoryItemId",
                                                "label": "Inventory Sub Category Item Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemMaintenance_inventorySubCategoryItemId",
                                                "alias" : "item_maintenance.inventory_sub_category_item_id"
                                            },
                                            {
                                                "name": "userRoleDesignationDepartmentId",
                                                "label": "User Role Designation Department Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemMaintenance_userRoleDesignationDepartmentId",
                                                "alias" : "item_maintenance.user_role_designation_department_id"
                                            },
                                            {
                                                "name": "inventoryBillId",
                                                "label": "Inventory Bill Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemMaintenance_inventoryBillId",
                                                "alias" : "item_maintenance.inventory_bill_id"
                                            },
                                            {
                                                "name": "description",
                                                "label": "Description",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemMaintenance_description",
                                                "alias" : "item_maintenance.description"
                                            },
                                            {
                                                "name": "maintenanceDate",
                                                "label": "Maintenance Date",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemMaintenance_maintenanceDate",
                                                "alias" : "item_maintenance.maintenance_date"
                                            },
                                            {
                                              "type": "listOfFields",
                                              "name": "options",
                                              "label": "Add Item Maintenance",
                                              "hideInCreateForm": true,

                                              "hideInViewForm": true,
                                              "title": "Select Item Maintenance",
                                              "dependancyCheck": false,
                                              "childFields": [
                                            
                                            ]
                                          }
                                        ,
                                        
                                            {
                                                "name": "updatedBy",
                                                "label": "Updated By",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemMaintenance_updatedBy",
                                                "alias" : "item_maintenance.updated_by"
                                            },
                                            {
                                                "name": "updatedAt",
                                                "label": "Updated At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemMaintenance_updatedAt",
                                                "alias" : "item_maintenance.updated_at"
                                            },
                                            {
                                                "name": "createdAt",
                                                "label": "Created At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemMaintenance_createdAt",
                                                "alias" : "item_maintenance.created_at"
                                            },
                                          
                                            {
                                                "name": "status",
                                                "label": "Status",
                                                "title": "",
                                                "type": "select",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemMaintenance_status",
                                                options:[
                                                    {value:'inactive',label:'inactive'},
                                                    {value:'active',label:'active'}
                                                ],
                                                "alias" : "item_maintenance.status"
                                            }

                                    ]
                                }
                            ]
                        },
                        "permission": "item_maintenance_view"
                    }                  
              ],
              "colMapper": { 'item_maintenance_itemMaintenanceId' : 'item_maintenance_id',  'item_maintenance_taskId' : 'task_id',  'item_maintenance_inventorySubCategoryItemId' : 'inventory_sub_category_item_id',  'item_maintenance_userRoleDesignationDepartmentId' : 'user_role_designation_department_id',  'item_maintenance_inventoryBillId' : 'inventory_bill_id',  'item_maintenance_description' : 'description',  'item_maintenance_maintenanceDate' : 'maintenance_date',  'item_maintenance_status' : 'status',  'item_maintenance_updatedBy' : 'updated_by',  'item_maintenance_updatedAt' : 'updated_at',  'item_maintenance_createdAt' : 'created_at'}
          };