export const parameters = {
              "steps": [
                
                    {
                        "title": "item_location Info",
                        "parameters": {
                            "fields": [
                                {
                                    "name": "itemLocation",
                                    "type": "section",
                                    "hideInCreateForm": false,
                                    "visible": false,
                                    "required": false,
                                    "disabled": false,
                                    "validations": "",
                                    "dependancyCheck": false,
                                    "isPrefilled": false,
                                    "source": "req.body",
                                    "title": "ItemLocation",
                                    "childFields": [
                                            {
                                              "name": "id",
                                              "label": "id",
                                              "title": "",
                                              "type": "textField",
                                              "required": false,
                                              "hideInCreateForm": true,
                                              "hideInViewForm" : true,
                                              "visible": false,
                                              "disabled": false,
                                              "dependancyCheck": false,
                                              "isPrefilled": false,
                                              "source": "req.query",
                                              "min": "",
                                              "max": "",
                                              "selectServer": false,
                                              "dynamicKey": "id",
                                              "alias" : "item_location.id"

                                            },
                                        
                                            {
                                                "name": "inventorySubCategoryItemId",
                                                "label": "Inventory Sub Category Item Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemLocation_inventorySubCategoryItemId",
                                                "alias" : "item_location.inventory_sub_category_item_id"
                                            },
                                            {
                                                "name": "locationName",
                                                "label": "Location Name",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemLocation_locationName",
                                                "alias" : "item_location.location_name"
                                            },
                                            {
                                                "name": "departureDate",
                                                "label": "Departure Date",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemLocation_departureDate",
                                                "alias" : "item_location.departure_date"
                                            },
                                            {
                                                "name": "arrivalDate",
                                                "label": "Arrival Date",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemLocation_arrivalDate",
                                                "alias" : "item_location.arrival_date"
                                            },
                                            {
                                                "name": "placedByUserRoleDesignationDepartmentId",
                                                "label": "Placed By User Role Designation Department Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemLocation_placedByUserRoleDesignationDepartmentId",
                                                "alias" : "item_location.placed_by_user_role_designation_department_id"
                                            },
                                            {
                                                "name": "displacedByUserRoleDesignationDepartmentId",
                                                "label": "Displaced By User Role Designation Department Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemLocation_displacedByUserRoleDesignationDepartmentId",
                                                "alias" : "item_location.displaced_by_user_role_designation_department_id"
                                            },
                                            {
                                              "type": "listOfFields",
                                              "name": "options",
                                              "label": "Add Item Location",
                                              "hideInCreateForm": true,

                                              "hideInViewForm": true,
                                              "title": "Select Item Location",
                                              "dependancyCheck": false,
                                              "childFields": [
                                            
                                            ]
                                          }
                                        ,
                                        
                                            {
                                                "name": "updatedBy",
                                                "label": "Updated By",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemLocation_updatedBy",
                                                "alias" : "item_location.updated_by"
                                            },
                                            {
                                                "name": "updatedAt",
                                                "label": "Updated At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemLocation_updatedAt",
                                                "alias" : "item_location.updated_at"
                                            },
                                            {
                                                "name": "createdAt",
                                                "label": "Created At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemLocation_createdAt",
                                                "alias" : "item_location.created_at"
                                            },
                                          
                                            {
                                                "name": "status",
                                                "label": "Status",
                                                "title": "",
                                                "type": "select",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemLocation_status",
                                                options:[
                                                    {value:'inactive',label:'inactive'},
                                                    {value:'active',label:'active'}
                                                ],
                                                "alias" : "item_location.status"
                                            }

                                    ]
                                }
                            ]
                        },
                        "permission": "item_location_view"
                    }                  
              ],
              "colMapper": { 'item_location_itemLocationId' : 'item_location_id',  'item_location_inventorySubCategoryItemId' : 'inventory_sub_category_item_id',  'item_location_locationName' : 'location_name',  'item_location_departureDate' : 'departure_date',  'item_location_arrivalDate' : 'arrival_date',  'item_location_placedByUserRoleDesignationDepartmentId' : 'placed_by_user_role_designation_department_id',  'item_location_displacedByUserRoleDesignationDepartmentId' : 'displaced_by_user_role_designation_department_id',  'item_location_status' : 'status',  'item_location_updatedBy' : 'updated_by',  'item_location_updatedAt' : 'updated_at',  'item_location_createdAt' : 'created_at'}
          };