export const parameters = {
              "steps": [
                
                    {
                        "title": "item_allocation Info",
                        "parameters": {
                            "fields": [
                                {
                                    "name": "itemAllocation",
                                    "type": "section",
                                    "hideInCreateForm": false,
                                    "visible": false,
                                    "required": false,
                                    "disabled": false,
                                    "validations": "",
                                    "dependancyCheck": false,
                                    "isPrefilled": false,
                                    "source": "req.body",
                                    "title": "ItemAllocation",
                                    "childFields": [
                                            {
                                              "name": "id",
                                              "label": "id",
                                              "title": "",
                                              "type": "textField",
                                              "required": false,
                                              "hideInCreateForm": true,
                                              "hideInViewForm" : true,
                                              "visible": false,
                                              "disabled": false,
                                              "dependancyCheck": false,
                                              "isPrefilled": false,
                                              "source": "req.query",
                                              "min": "",
                                              "max": "",
                                              "selectServer": false,
                                              "dynamicKey": "id",
                                              "alias" : "item_allocation.id"

                                            },
                                        
                                            {
                                                "name": "taskId",
                                                "label": "Task Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_taskId",
                                                "alias" : "item_allocation.task_id"
                                            },
                                            {
                                                "name": "inventorySubCategoryItemId",
                                                "label": "Inventory Sub Category Item Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_inventorySubCategoryItemId",
                                                "alias" : "item_allocation.inventory_sub_category_item_id"
                                            },
                                            {
                                                "name": "allocatedTo",
                                                "label": "Allocated To",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_allocatedTo",
                                                "alias" : "item_allocation.allocated_to"
                                            },
                                            {
                                                "name": "allocatedBy",
                                                "label": "Allocated By",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_allocatedBy",
                                                "alias" : "item_allocation.allocated_by"
                                            },
                                            {
                                                "name": "allocatedOnBehalfOf",
                                                "label": "Allocated On Behalf Of",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_allocatedOnBehalfOf",
                                                "alias" : "item_allocation.allocated_on_behalf_of"
                                            },
                                            {
                                                "name": "returnBy",
                                                "label": "Return By",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_returnBy",
                                                "alias" : "item_allocation.return_by"
                                            },
                                            {
                                                "name": "returnTo",
                                                "label": "Return To",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_returnTo",
                                                "alias" : "item_allocation.return_to"
                                            },
                                            {
                                                "name": "returnDate",
                                                "label": "Return Date",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_returnDate",
                                                "alias" : "item_allocation.return_date"
                                            },
                                            {
                                                "name": "dueDate",
                                                "label": "Due Date",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_dueDate",
                                                "alias" : "item_allocation.due_date"
                                            },
                                            {
                                                "name": "allocatedDate",
                                                "label": "Allocated Date",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_allocatedDate",
                                                "alias" : "item_allocation.allocated_date"
                                            },
                                            {
                                              "type": "listOfFields",
                                              "name": "options",
                                              "label": "Add Item Allocation",
                                              "hideInCreateForm": true,

                                              "hideInViewForm": true,
                                              "title": "Select Item Allocation",
                                              "dependancyCheck": false,
                                              "childFields": [
                                            
                                            ]
                                          }
                                        ,
                                        
                                            {
                                                "name": "updatedBy",
                                                "label": "Updated By",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_updatedBy",
                                                "alias" : "item_allocation.updated_by"
                                            },
                                            {
                                                "name": "updatedAt",
                                                "label": "Updated At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_updatedAt",
                                                "alias" : "item_allocation.updated_at"
                                            },
                                            {
                                                "name": "createdAt",
                                                "label": "Created At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_createdAt",
                                                "alias" : "item_allocation.created_at"
                                            },
                                          
                                            {
                                                "name": "status",
                                                "label": "Status",
                                                "title": "",
                                                "type": "select",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "itemAllocation_status",
                                                options:[
                                                    {value:'inactive',label:'inactive'},
                                                    {value:'active',label:'active'}
                                                ],
                                                "alias" : "item_allocation.status"
                                            }

                                    ]
                                }
                            ]
                        },
                        "permission": "item_allocation_view"
                    }                  
              ],
              "colMapper": { 'item_allocation_itemAllocationId' : 'item_allocation_id',  'item_allocation_taskId' : 'task_id',  'item_allocation_inventorySubCategoryItemId' : 'inventory_sub_category_item_id',  'item_allocation_allocatedTo' : 'allocated_to',  'item_allocation_allocatedBy' : 'allocated_by',  'item_allocation_allocatedOnBehalfOf' : 'allocated_on_behalf_of',  'item_allocation_returnBy' : 'return_by',  'item_allocation_returnTo' : 'return_to',  'item_allocation_returnDate' : 'return_date',  'item_allocation_dueDate' : 'due_date',  'item_allocation_allocatedDate' : 'allocated_date',  'item_allocation_status' : 'status',  'item_allocation_updatedBy' : 'updated_by',  'item_allocation_updatedAt' : 'updated_at',  'item_allocation_createdAt' : 'created_at'}
          };