const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "user_devices",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "User_devices",
                        "childFields": [
                            
                                {
                                "name": "user_device_id",
                                "label": "User Device Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_devices_userDeviceId",
                                "alias" : "user_devices.user_device_id",
                                },
                                {
                                "name": "user_id",
                                "label": "User Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_devices_userId",
                                "alias" : "user_devices.user_id",
                                },
                                {
                                "name": "device_token",
                                "label": "Device Token",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_devices_deviceToken",
                                "alias" : "user_devices.device_token",
                                },
                                {
                                "name": "user_id",
                                "label": "User Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_devices_userId",
                                "alias" : "user_devices.user_id",
                                },
                                {
                                "name": "device_token",
                                "label": "Device Token",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_devices_deviceToken",
                                "alias" : "user_devices.device_token",
                                },
                                {
                                "name": "device_name",
                                "label": "Device Name",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_devices_deviceName",
                                "alias" : "user_devices.device_name",
                                },
                                {
                                "name": "platform_version_id",
                                "label": "Platform Version Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_devices_platformVersionId",
                                "alias" : "user_devices.platform_version_id",
                                },
                                {
                                "name": "os_version",
                                "label": "Os Version",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_devices_osVersion",
                                "alias" : "user_devices.os_version",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "user_devices_updatedBy",
                                "alias" : "user_devices.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'user_devices_userDeviceId' : 'user_device_id',  'user_devices_userId' : 'user_id',  'user_devices_deviceToken' : 'device_token',  'user_devices_status' : 'status',  'user_devices_userId' : 'user_id',  'user_devices_deviceToken' : 'device_token',  'user_devices_status' : 'status',  'user_devices_deviceName' : 'device_name',  'user_devices_platformVersionId' : 'platform_version_id',  'user_devices_osVersion' : 'os_version',  'user_devices_updatedBy' : 'updated_by',  'user_devices_updatedAt' : 'updated_at',  'user_devices_createdAt' : 'created_at'}"
            };
            module.exports = parameters;