export const parameters = {
              "steps": [
                
                    {
                        "title": "bill_payment Info",
                        "parameters": {
                            "fields": [
                                {
                                    "name": "billPayment",
                                    "type": "section",
                                    "hideInCreateForm": false,
                                    "visible": false,
                                    "required": false,
                                    "disabled": false,
                                    "validations": "",
                                    "dependancyCheck": false,
                                    "isPrefilled": false,
                                    "source": "req.body",
                                    "title": "BillPayment",
                                    "childFields": [
                                            {
                                              "name": "id",
                                              "label": "id",
                                              "title": "",
                                              "type": "textField",
                                              "required": false,
                                              "hideInCreateForm": true,
                                              "hideInViewForm" : true,
                                              "visible": false,
                                              "disabled": false,
                                              "dependancyCheck": false,
                                              "isPrefilled": false,
                                              "source": "req.query",
                                              "min": "",
                                              "max": "",
                                              "selectServer": false,
                                              "dynamicKey": "id",
                                              "alias" : "bill_payment.id"

                                            },
                                        
                                            {
                                                "name": "inventoryBillId",
                                                "label": "Inventory Bill Id",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "billPayment_inventoryBillId",
                                                "alias" : "bill_payment.inventory_bill_id"
                                            },
                                            {
                                                "name": "paymentBy",
                                                "label": "Payment By",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "billPayment_paymentBy",
                                                "alias" : "bill_payment.payment_by"
                                            },
                                            {
                                                "name": "dueDate",
                                                "label": "Due Date",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "billPayment_dueDate",
                                                "alias" : "bill_payment.due_date"
                                            },
                                            {
                                                "name": "totalPayment",
                                                "label": "Total Payment",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "billPayment_totalPayment",
                                                "alias" : "bill_payment.total_payment"
                                            },
                                            {
                                                "name": "remainingPayment",
                                                "label": "Remaining Payment",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "billPayment_remainingPayment",
                                                "alias" : "bill_payment.remaining_payment"
                                            },
                                            {
                                                "name": "paymentMethod",
                                                "label": "Payment Method",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "billPayment_paymentMethod",
                                                "alias" : "bill_payment.payment_method"
                                            },
                                            {
                                                "name": "lastPaymentDate",
                                                "label": "Last Payment Date",
                                                "title": "",
                                                "type": "textField",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "billPayment_lastPaymentDate",
                                                "alias" : "bill_payment.last_payment_date"
                                            },
                                            {
                                              "type": "listOfFields",
                                              "name": "options",
                                              "label": "Add Bill Payment",
                                              "hideInCreateForm": true,

                                              "hideInViewForm": true,
                                              "title": "Select Bill Payment",
                                              "dependancyCheck": false,
                                              "childFields": [
                                            
                                            ]
                                          }
                                        ,
                                        
                                            {
                                                "name": "updatedBy",
                                                "label": "Updated By",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "billPayment_updatedBy",
                                                "alias" : "bill_payment.updated_by"
                                            },
                                            {
                                                "name": "updatedAt",
                                                "label": "Updated At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "billPayment_updatedAt",
                                                "alias" : "bill_payment.updated_at"
                                            },
                                            {
                                                "name": "createdAt",
                                                "label": "Created At",
                                                "title": "",
                                                "type": "dateTime",
                                                "required": false,
                                                "hideInCreateForm": true,
                                                "hideInViewForm" : true,
                                                "visible": false,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "billPayment_createdAt",
                                                "alias" : "bill_payment.created_at"
                                            },
                                          
                                            {
                                                "name": "status",
                                                "label": "Status",
                                                "title": "",
                                                "type": "select",
                                                "required": false,
                                                "hideInCreateForm": false,
                                                "visible": true,
                                                "disabled": false,
                                                "dependancyCheck": false,
                                                "isPrefilled": false,
                                                "source": "req.body",
                                                "min": "",
                                                "max": "",
                                                "validations": [],
                                                "selectServer": false,
                                                "dynamicKey": "billPayment_status",
                                                options:[
                                                    {value:'inactive',label:'inactive'},
                                                    {value:'active',label:'active'}
                                                ],
                                                "alias" : "bill_payment.status"
                                            }

                                    ]
                                }
                            ]
                        },
                        "permission": "bill_payment_view"
                    }                  
              ],
              "colMapper": { 'bill_payment_billPaymentId' : 'bill_payment_id',  'bill_payment_inventoryBillId' : 'inventory_bill_id',  'bill_payment_paymentBy' : 'payment_by',  'bill_payment_dueDate' : 'due_date',  'bill_payment_totalPayment' : 'total_payment',  'bill_payment_remainingPayment' : 'remaining_payment',  'bill_payment_paymentMethod' : 'payment_method',  'bill_payment_lastPaymentDate' : 'last_payment_date',  'bill_payment_status' : 'status',  'bill_payment_updatedBy' : 'updated_by',  'bill_payment_updatedAt' : 'updated_at',  'bill_payment_createdAt' : 'created_at'}
          };