const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "inventory",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "Inventory",
                        "childFields": [
                            
                                {
                                "name": "inventory_id",
                                "label": "Inventory Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_inventoryId",
                                "alias" : "inventory.inventory_id",
                                },
                                {
                                "name": "department_id",
                                "label": "Department Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_departmentId",
                                "alias" : "inventory.department_id",
                                },
                                {
                                "name": "current_campus_id",
                                "label": "Current Campus Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_currentCampusId",
                                "alias" : "inventory.current_campus_id",
                                },
                                {
                                "name": "previous_campus_id",
                                "label": "Previous Campus Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_previousCampusId",
                                "alias" : "inventory.previous_campus_id",
                                },
                                {
                                "name": "inventory_name",
                                "label": "Inventory Name",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_inventoryName",
                                "alias" : "inventory.inventory_name",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "inventory_updatedBy",
                                "alias" : "inventory.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'inventory_inventoryId' : 'inventory_id',  'inventory_departmentId' : 'department_id',  'inventory_currentCampusId' : 'current_campus_id',  'inventory_previousCampusId' : 'previous_campus_id',  'inventory_inventoryName' : 'inventory_name',  'inventory_status' : 'status',  'inventory_updatedBy' : 'updated_by',  'inventory_updatedAt' : 'updated_at',  'inventory_createdAt' : 'created_at'}"
            };
            module.exports = parameters;