const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "notifications",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "Notifications",
                        "childFields": [
                            
                                {
                                "name": "notification_id",
                                "label": "Notification Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "notifications_notificationId",
                                "alias" : "notifications.notification_id",
                                },
                                {
                                "name": "notification_title",
                                "label": "Notification Title",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "notifications_notificationTitle",
                                "alias" : "notifications.notification_title",
                                },
                                {
                                "name": "notification_title",
                                "label": "Notification Title",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "notifications_notificationTitle",
                                "alias" : "notifications.notification_title",
                                },
                                {
                                "name": "notification_message",
                                "label": "Notification Message",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "notifications_notificationMessage",
                                "alias" : "notifications.notification_message",
                                },
                                {
                                "name": "sent_to_user_role_designation_department_id",
                                "label": "Sent To User Role Designation Department Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "notifications_sentToUserRoleDesignationDepartmentId",
                                "alias" : "notifications.sent_to_user_role_designation_department_id",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "notifications_updatedBy",
                                "alias" : "notifications.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'notifications_notificationId' : 'notification_id',  'notifications_notificationTitle' : 'notification_title',  'notifications_status' : 'status',  'notifications_notificationTitle' : 'notification_title',  'notifications_status' : 'status',  'notifications_notificationMessage' : 'notification_message',  'notifications_sentToUserRoleDesignationDepartmentId' : 'sent_to_user_role_designation_department_id',  'notifications_updatedBy' : 'updated_by',  'notifications_updatedAt' : 'updated_at',  'notifications_createdAt' : 'created_at'}"
            };
            module.exports = parameters;