const parameters = {
            "steps": [
                
                        {
                            "title": "item_allocation Info",
                            "parameters": {
                                "fields": [
                                    {
                                        "name": "item_allocation",
                                        "type": "section",
                                        "hideInCreateForm": false,
                                        "visible": false,
                                        "required": false,
                                        "disabled": false,
                                        "validations": "",
                                        "dependancyCheck": false,
                                        "isPrefilled": false,
                                        "source": "req.body",
                                        "title": "Item_allocation",
                                        "childFields": [
                                                {
                                                        "name": "id",
                                                        "label": "id",
                                                        "title": "",
                                                        "type": "textField",
                                                        "required": false,
                                                        "hideInCreateForm": true,
                                                        "visible": true,
                                                        "disabled": false,
                                                        "dependancyCheck": false,
                                                        "isPrefilled": false,
                                                        "source": "req.query",
                                                        "min": "",
                                                        "max": "",
                                                        "selectServer": false,
                                                        "dynamicKey": "id"
                                                },
                                            
                                                    {
                                                        "name": "taskId",
                                                        "label": "Task Id",
                                                        "title": "",
                                                        "type": "textField",
                                                        "required": false,
                                                        "hideInCreateForm": false,
                                                        "visible": true,
                                                        "disabled": false,
                                                        "dependancyCheck": false,
                                                        "isPrefilled": false,
                                                        "source": "req.body",
                                                        "min": "",
                                                        "max": "",
                                                        "selectServer": false,
                                                        "dynamicKey": "item_allocation_taskId"
                                                    },
                                                    {
                                                        "name": "inventorySubCategoryItemId",
                                                        "label": "Inventory Sub Category Item Id",
                                                        "title": "",
                                                        "type": "textField",
                                                        "required": false,
                                                        "hideInCreateForm": false,
                                                        "visible": true,
                                                        "disabled": false,
                                                        "dependancyCheck": false,
                                                        "isPrefilled": false,
                                                        "source": "req.body",
                                                        "min": "",
                                                        "max": "",
                                                        "selectServer": false,
                                                        "dynamicKey": "item_allocation_inventorySubCategoryItemId"
                                                    },
                                                    {
                                                        "name": "allocatedTo",
                                                        "label": "Allocated To",
                                                        "title": "",
                                                        "type": "textField",
                                                        "required": false,
                                                        "hideInCreateForm": false,
                                                        "visible": true,
                                                        "disabled": false,
                                                        "dependancyCheck": false,
                                                        "isPrefilled": false,
                                                        "source": "req.body",
                                                        "min": "",
                                                        "max": "",
                                                        "selectServer": false,
                                                        "dynamicKey": "item_allocation_allocatedTo"
                                                    },
                                                    {
                                                        "name": "allocatedBy",
                                                        "label": "Allocated By",
                                                        "title": "",
                                                        "type": "textField",
                                                        "required": false,
                                                        "hideInCreateForm": false,
                                                        "visible": true,
                                                        "disabled": false,
                                                        "dependancyCheck": false,
                                                        "isPrefilled": false,
                                                        "source": "req.body",
                                                        "min": "",
                                                        "max": "",
                                                        "selectServer": false,
                                                        "dynamicKey": "item_allocation_allocatedBy"
                                                    },
                                                    {
                                                        "name": "allocatedOnBehalfOf",
                                                        "label": "Allocated On Behalf Of",
                                                        "title": "",
                                                        "type": "textField",
                                                        "required": false,
                                                        "hideInCreateForm": false,
                                                        "visible": true,
                                                        "disabled": false,
                                                        "dependancyCheck": false,
                                                        "isPrefilled": false,
                                                        "source": "req.body",
                                                        "min": "",
                                                        "max": "",
                                                        "selectServer": false,
                                                        "dynamicKey": "item_allocation_allocatedOnBehalfOf"
                                                    },
                                                    {
                                                        "name": "returnBy",
                                                        "label": "Return By",
                                                        "title": "",
                                                        "type": "textField",
                                                        "required": false,
                                                        "hideInCreateForm": false,
                                                        "visible": true,
                                                        "disabled": false,
                                                        "dependancyCheck": false,
                                                        "isPrefilled": false,
                                                        "source": "req.body",
                                                        "min": "",
                                                        "max": "",
                                                        "selectServer": false,
                                                        "dynamicKey": "item_allocation_returnBy"
                                                    },
                                                    {
                                                        "name": "returnTo",
                                                        "label": "Return To",
                                                        "title": "",
                                                        "type": "textField",
                                                        "required": false,
                                                        "hideInCreateForm": false,
                                                        "visible": true,
                                                        "disabled": false,
                                                        "dependancyCheck": false,
                                                        "isPrefilled": false,
                                                        "source": "req.body",
                                                        "min": "",
                                                        "max": "",
                                                        "selectServer": false,
                                                        "dynamicKey": "item_allocation_returnTo"
                                                    },
                                                    {
                                                        "name": "returnDate",
                                                        "label": "Return Date",
                                                        "title": "",
                                                        "type": "textField",
                                                        "required": false,
                                                        "hideInCreateForm": false,
                                                        "visible": true,
                                                        "disabled": false,
                                                        "dependancyCheck": false,
                                                        "isPrefilled": false,
                                                        "source": "req.body",
                                                        "min": "",
                                                        "max": "",
                                                        "selectServer": false,
                                                        "dynamicKey": "item_allocation_returnDate"
                                                    },
                                                    {
                                                        "name": "dueDate",
                                                        "label": "Due Date",
                                                        "title": "",
                                                        "type": "textField",
                                                        "required": false,
                                                        "hideInCreateForm": false,
                                                        "visible": true,
                                                        "disabled": false,
                                                        "dependancyCheck": false,
                                                        "isPrefilled": false,
                                                        "source": "req.body",
                                                        "min": "",
                                                        "max": "",
                                                        "selectServer": false,
                                                        "dynamicKey": "item_allocation_dueDate"
                                                    },
                                                    {
                                                        "name": "allocatedDate",
                                                        "label": "Allocated Date",
                                                        "title": "",
                                                        "type": "textField",
                                                        "required": false,
                                                        "hideInCreateForm": false,
                                                        "visible": true,
                                                        "disabled": false,
                                                        "dependancyCheck": false,
                                                        "isPrefilled": false,
                                                        "source": "req.body",
                                                        "min": "",
                                                        "max": "",
                                                        "selectServer": false,
                                                        "dynamicKey": "item_allocation_allocatedDate"
                                                    },
                                                    {
                                                        "name": "updatedBy",
                                                        "label": "Updated By",
                                                        "title": "",
                                                        "type": "textField",
                                                        "required": false,
                                                        "hideInCreateForm": false,
                                                        "visible": true,
                                                        "disabled": false,
                                                        "dependancyCheck": false,
                                                        "isPrefilled": false,
                                                        "source": "req.body",
                                                        "min": "",
                                                        "max": "",
                                                        "selectServer": false,
                                                        "dynamicKey": "item_allocation_updatedBy"
                                                    }
                                        ]
                                    }
                                ]
                            },
                            "buttons": [
                                {
                                    "type": "submit",
                                    "label": "Submit"
                                }
                            ],
                            "permission": "item_allocation_view"
                        }
            ],
            "colMapper": "{ 'item_allocation_itemAllocationId' : 'item_allocation_id',  'item_allocation_taskId' : 'task_id',  'item_allocation_inventorySubCategoryItemId' : 'inventory_sub_category_item_id',  'item_allocation_allocatedTo' : 'allocated_to',  'item_allocation_allocatedBy' : 'allocated_by',  'item_allocation_allocatedOnBehalfOf' : 'allocated_on_behalf_of',  'item_allocation_returnBy' : 'return_by',  'item_allocation_returnTo' : 'return_to',  'item_allocation_returnDate' : 'return_date',  'item_allocation_dueDate' : 'due_date',  'item_allocation_allocatedDate' : 'allocated_date',  'item_allocation_status' : 'status',  'item_allocation_updatedBy' : 'updated_by',  'item_allocation_updatedAt' : 'updated_at',  'item_allocation_createdAt' : 'created_at'}"
        };
        module.exports = parameters;