const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "item_allocation",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "Item_allocation",
                        "childFields": [
                            
                                {
                                "name": "item_allocation_id",
                                "label": "Item Allocation Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_allocation_itemAllocationId",
                                "alias" : "item_allocation.item_allocation_id",
                                },
                                {
                                "name": "task_id",
                                "label": "Task Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_allocation_taskId",
                                "alias" : "item_allocation.task_id",
                                },
                                {
                                "name": "inventory_sub_category_item_id",
                                "label": "Inventory Sub Category Item Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_allocation_inventorySubCategoryItemId",
                                "alias" : "item_allocation.inventory_sub_category_item_id",
                                },
                                {
                                "name": "allocated_to",
                                "label": "Allocated To",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_allocation_allocatedTo",
                                "alias" : "item_allocation.allocated_to",
                                },
                                {
                                "name": "allocated_by",
                                "label": "Allocated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_allocation_allocatedBy",
                                "alias" : "item_allocation.allocated_by",
                                },
                                {
                                "name": "allocated_on_behalf_of",
                                "label": "Allocated On Behalf Of",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_allocation_allocatedOnBehalfOf",
                                "alias" : "item_allocation.allocated_on_behalf_of",
                                },
                                {
                                "name": "return_by",
                                "label": "Return By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_allocation_returnBy",
                                "alias" : "item_allocation.return_by",
                                },
                                {
                                "name": "return_to",
                                "label": "Return To",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_allocation_returnTo",
                                "alias" : "item_allocation.return_to",
                                },
                                {
                                "name": "return_date",
                                "label": "Return Date",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_allocation_returnDate",
                                "alias" : "item_allocation.return_date",
                                },
                                {
                                "name": "due_date",
                                "label": "Due Date",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_allocation_dueDate",
                                "alias" : "item_allocation.due_date",
                                },
                                {
                                "name": "allocated_date",
                                "label": "Allocated Date",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_allocation_allocatedDate",
                                "alias" : "item_allocation.allocated_date",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "item_allocation_updatedBy",
                                "alias" : "item_allocation.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'item_allocation_itemAllocationId' : 'item_allocation_id',  'item_allocation_taskId' : 'task_id',  'item_allocation_inventorySubCategoryItemId' : 'inventory_sub_category_item_id',  'item_allocation_allocatedTo' : 'allocated_to',  'item_allocation_allocatedBy' : 'allocated_by',  'item_allocation_allocatedOnBehalfOf' : 'allocated_on_behalf_of',  'item_allocation_returnBy' : 'return_by',  'item_allocation_returnTo' : 'return_to',  'item_allocation_returnDate' : 'return_date',  'item_allocation_dueDate' : 'due_date',  'item_allocation_allocatedDate' : 'allocated_date',  'item_allocation_status' : 'status',  'item_allocation_updatedBy' : 'updated_by',  'item_allocation_updatedAt' : 'updated_at',  'item_allocation_createdAt' : 'created_at'}"
            };
            module.exports = parameters;