const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "task_flow_steps",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "Task_flow_steps",
                        "childFields": [
                            
                                {
                                "name": "task_flow_step_id",
                                "label": "Task Flow Step Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flow_steps_taskFlowStepId",
                                "alias" : "task_flow_steps.task_flow_step_id",
                                },
                                {
                                "name": "task_flow_id",
                                "label": "Task Flow Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flow_steps_taskFlowId",
                                "alias" : "task_flow_steps.task_flow_id",
                                },
                                {
                                "name": "step_title",
                                "label": "Step Title",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flow_steps_stepTitle",
                                "alias" : "task_flow_steps.step_title",
                                },
                                {
                                "name": "step_order",
                                "label": "Step Order",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flow_steps_stepOrder",
                                "alias" : "task_flow_steps.step_order",
                                },
                                {
                                "name": "step_description",
                                "label": "Step Description",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flow_steps_stepDescription",
                                "alias" : "task_flow_steps.step_description",
                                },
                                {
                                "name": "is_cross_department",
                                "label": "Is Cross Department",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flow_steps_isCrossDepartment",
                                "alias" : "task_flow_steps.is_cross_department",
                                },
                                {
                                "name": "step_assigned_to_role_department_id",
                                "label": "Step Assigned To Role Department Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flow_steps_stepAssignedToRoleDepartmentId",
                                "alias" : "task_flow_steps.step_assigned_to_role_department_id",
                                },
                                {
                                "name": "created_by_user_role_department_id",
                                "label": "Created By User Role Department Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flow_steps_createdByUserRoleDepartmentId",
                                "alias" : "task_flow_steps.created_by_user_role_department_id",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "task_flow_steps_updatedBy",
                                "alias" : "task_flow_steps.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'task_flow_steps_taskFlowStepId' : 'task_flow_step_id',  'task_flow_steps_taskFlowId' : 'task_flow_id',  'task_flow_steps_stepTitle' : 'step_title',  'task_flow_steps_stepOrder' : 'step_order',  'task_flow_steps_status' : 'status',  'task_flow_steps_stepDescription' : 'step_description',  'task_flow_steps_isCrossDepartment' : 'is_cross_department',  'task_flow_steps_stepAssignedToRoleDepartmentId' : 'step_assigned_to_role_department_id',  'task_flow_steps_createdByUserRoleDepartmentId' : 'created_by_user_role_department_id',  'task_flow_steps_updatedAt' : 'updated_at',  'task_flow_steps_createdAt' : 'created_at',  'task_flow_steps_updatedBy' : 'updated_by'}"
            };
            module.exports = parameters;