const parameters = {
            "steps": [
                {
                "title": "Step 1",
                "parameters": {
                    "fields": [
                    {
                        "name": "attachments",
                        "type": "section",
                        "hideInCreateForm": false,
                        "visible": false,
                        "required": false,
                        "disabled": false,
                        "validations": "",
                        "dependancyCheck": false,
                        "isPrefilled": false,
                        "source": "req.body",
                        "title": "Attachments",
                        "childFields": [
                            
                                {
                                "name": "attachment_id",
                                "label": "Attachment Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "attachments_attachmentId",
                                "alias" : "attachments.attachment_id",
                                },
                                {
                                "name": "attachment_name",
                                "label": "Attachment Name",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "attachments_attachmentName",
                                "alias" : "attachments.attachment_name",
                                },
                                {
                                "name": "attachment_name",
                                "label": "Attachment Name",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "attachments_attachmentName",
                                "alias" : "attachments.attachment_name",
                                },
                                {
                                "name": "uploaded_by_user_role_designation_department_id",
                                "label": "Uploaded By User Role Designation Department Id",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "attachments_uploadedByUserRoleDesignationDepartmentId",
                                "alias" : "attachments.uploaded_by_user_role_designation_department_id",
                                },
                                {
                                "name": "attachment_type",
                                "label": "Attachment Type",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "attachments_attachmentType",
                                "alias" : "attachments.attachment_type",
                                },
                                {
                                "name": "attachment_size",
                                "label": "Attachment Size",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "attachments_attachmentSize",
                                "alias" : "attachments.attachment_size",
                                },
                                {
                                "name": "attachment_link",
                                "label": "Attachment Link",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "attachments_attachmentLink",
                                "alias" : "attachments.attachment_link",
                                },
                                {
                                "name": "updated_by",
                                "label": "Updated By",
                                "title": "",
                                "type": "textField",
                                "required": false,
                                "hideInCreateForm": false,
                                "visible": true,
                                "disabled": false,
                                "dependancyCheck": false,
                                "isPrefilled": false,
                                "source": "req.body",
                                "min": "",
                                "max": "",
                                "selectServer": false,
                                "dynamicKey": "attachments_updatedBy",
                                "alias" : "attachments.updated_by",
                                },
                                
                        ]
                    }
                    ]
                },
                "buttons": [
                    {
                    "type": "submit",
                    "label": "Submit"
                    }
                ]
                }
            ],
            "colMapper": "{ 'attachments_attachmentId' : 'attachment_id',  'attachments_attachmentName' : 'attachment_name',  'attachments_status' : 'status',  'attachments_attachmentName' : 'attachment_name',  'attachments_status' : 'status',  'attachments_uploadedByUserRoleDesignationDepartmentId' : 'uploaded_by_user_role_designation_department_id',  'attachments_attachmentType' : 'attachment_type',  'attachments_attachmentSize' : 'attachment_size',  'attachments_attachmentLink' : 'attachment_link',  'attachments_updatedBy' : 'updated_by',  'attachments_createdAt' : 'created_at',  'attachments_updatedAt' : 'updated_at'}"
            };
            module.exports = parameters;